#spring.datasource.url=jdbc:mysql://localhost:3306/contract_db
#spring.datasource.username=root
#spring.datasource.password=your_password
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode:always
  security:
    user:
      name: admin
      password: admin123


jwt:
  secret: my-secret-key-which-is-very-secure
  expiration: 86400000
